// Complete utility strings keep Tailwind detection reliable for dynamic slide layouts.
export const slideClasses = {
  "slide": "slide min-h-full w-full max-w-[1600px] flex flex-col justify-center gap-[25px] relative isolate py-[clamp(26px,4.2vh,52px)] px-[7.5vw] m-auto [&>*]:animate-arrive [&>*:nth-child(2)]:[animation-delay:45ms] [&>*:nth-child(3)]:[animation-delay:90ms] [&>*:nth-child(4)]:[animation-delay:130ms] [&.cover]:max-w-none [&.cover]:[background:url(/assets/cover.png)_center/cover_no-repeat] [&.cover]:justify-center [&.cover]:pl-[7.5vw] [&.cover]:gap-0 wide:[&:not(.cover)]:px-[115px] compact:gap-[20px] compact:py-[25px] tablet:gap-[25px] tablet:py-[35px] tablet:px-[6vw] mobile:[justify-content:flex-start] mobile:gap-[23px] mobile:py-[30px] mobile:px-[23px]",
  "cover": "cover [&:before]:[content:''] [&:before]:absolute [&:before]:inset-0 [&:before]:[background:linear-gradient(_90deg,rgba(246,249,251,0.97)_0%,rgba(246,249,251,0.89)_24%,rgba(246,249,251,0.27)_48%,transparent_67%_)] [&:before]:z-[-1] [&_.eyebrow]:flex [&_.eyebrow]:gap-[12px] [&_.eyebrow]:items-center [&_.eyebrow]:text-blue [&_.eyebrow]:mb-[24px] [&_h1]:text-[clamp(62px,7.8vw,118px)] [&_h1]:leading-[0.96] [&_h1]:tracking-[-5px] [&_h1]:font-normal [&_h1_span]:text-blue [&_h1_i]:not-italic [&_h1_i]:text-orange [&_.primary]:mt-[29px] compact:[&_h1]:text-[clamp(60px,7vw,97px)] compact:[&_.eyebrow]:mb-[19px] compact:[&_.primary]:mt-[21px] tablet:[&_h1]:text-[76px] tablet:[&:before]:[background:linear-gradient(90deg,#f4f8fbf5,#f4f8fbd4_40%,#f4f8fb25)] mobile:justify-center! mobile:[background-position:62%_center]! mobile:[&:before]:[background:linear-gradient(90deg,#f4f8fbef_12%,#f4f8fbc9_60%,#f4f8fb50)] mobile:[&_h1]:text-[clamp(51px,12.9vw,77px)] mobile:[&_h1]:tracking-[-3px] mobile:[&_.primary]:text-[13px] mobile:[&_.primary]:py-[15px] mobile:[&_.primary]:px-[20px]",
  "manifesto": "manifesto [background:linear-gradient(90deg,#f7f8f9_40%,#e8eff5)]",
  "discussion": "discussion overflow-hidden [background:#eaf0f5] [&_h2]:max-w-[80%] [&_h2]:text-[clamp(40px,5.2vw,78px)] mobile:[&_h2]:text-[38px] mobile:[&_h2]:max-w-full",
  "decision-intro": "decision-intro [background:linear-gradient(130deg,#f7f8f9,#e3ecf4)] [&>.bottom-thought]:text-center",
  "closing": "closing [background:linear-gradient(0deg,#f7f8f9ee,#f7f8f9e8),url(/assets/mountains.png)_center_70%_/_cover]"
};
